### PR TITLE
Implement v3 anthropic client (bedrock support)

### PR DESCRIPTION
**Pull request by pigeonlaser**
@madebywelch here's the WIP branch for bedrock support and minor restructuring to support 2 clients.

I landed on this structure:
```
anthropic/
|---client/
    |---client.go (client interface is declared here)
    |---native/
        |---{code native to anthropic api}
    |---bedrock/
        |---{code for hitting anthropic on bedrock}
|---utils/
    |---{copied over utils from v2}
|---{All other files are generic anthropic, ported over from v2 and used by both clients}
```

What's done:
- Bedrock Client
- Native Anthropic Client

What I'm still working on:
- Support the error types in errors.go for Bedrock
- Unit testing
- Switch over integration testing to new clients
- Switch over examples to new clients
- Update README

I'm planning on having the rest of these items wrapped up by EOD tomorrow. Let me know your thoughts!

### CODE REVIEW

**Comment by pigeonlaser** [comment]
Added unit tests for all the files in the anthropic package. (still need to finish up some in validate.go)

I'll get to the rest of the unit testing tonight/tomorrow

**Comment by pigeonlaser** [comment]
@madebywelch ready for review!

I would like to get unit tests in bedrock, but the aws-sdk has a special way of unit testing that I don't currently have the time to set up.

**Comment by madebywelch** [comment]
@pigeonlaser Awesome, great work! I'll try and QA this weekend.

**Comment by madebywelch** [comment]
I haven't forgotten about this by the way. Just looking for time to review it thoroughly. @pigeonlaser

**Comment by madebywelch** [comment]
I made a few changes and merged it. Thank you for all your effort.

**Pull request closed without merging**
