### PR TITLE
Add image support

### PR DESCRIPTION
**Pull request by madebywelch**

### CODE REVIEW

**Comment by madebywelch** [comment]
Thoughts on this design? @pigeonlaser @molizz @lakshmanpasala

**Comment by lakshmanpasala** [comment]
Exactly what I had in mind. 

We can update `IsImageCompatible` to also check:
- The supported file formats i.e.

>  Claude currently support JPEG, PNG, GIF, and WebP image formats, specifically `image/jpeg`, `image/png`, `image/gif`, and `image/webp`.

- The file size per image i.e. 

> Yes, the maximum allowed image file size is 5MB per image (10MB per image on [claude.ai](https://claude.ai/)). Images larger than 5MB will be rejected and return an error when using our API.

and have another function to check for a maximum of 20 images in the request.

**Comment by madebywelch** [comment]
> Exactly what I had in mind.
> 
> We can update `IsImageCompatible` to also check:
> 
> * The supported file formats i.e.
> 
> > Claude currently support JPEG, PNG, GIF, and WebP image formats, specifically `image/jpeg`, `image/png`, `image/gif`, and `image/webp`.
> 
> * The file size per image i.e.
> 
> > Yes, the maximum allowed image file size is 5MB per image (10MB per image on [claude.ai](https://claude.ai/)). Images larger than 5MB will be rejected and return an error when using our API.
> 
> and have another function to check for a maximum of 20 images in the request.

Good idea. I added a MediaType and a logical check to error if > 20 images are in the request. Thoughts on latest?

**Comment by pigeonlaser** [comment]
> Thoughts on this design? @pigeonlaser @molizz @lakshmanpasala

I’ll check it out later tonight!

**Comment by pigeonlaser** [comment]
> > Thoughts on this design? @pigeonlaser @molizz @lakshmanpasala
> 
> I’ll check it out later tonight!

sorry for the delay, looks good to me!

**Pull request merged**
